------------JOINS--------

--CREATE TABLES AND SEED DATA--
CREATE TABLE MYEMLOYEE(EMPLOYEID INT, FIRSTNAME VARCHAR(20), LASTNAME VARCHAR(20))
INSERT INTO MYEMLOYEE VALUES(1,'Michael', 'Scott')
INSERT INTO MYEMLOYEE VALUES(2,'Pam', 'Beesly')
INSERT INTO MYEMLOYEE VALUES(3,'Dwight', 'Schrute')


CREATE TABLE MYSALARY (EMPLOYEEID INT, SALARY FLOAT)
INSERT INTO MYSALARY VALUES(1,10000)
INSERT INTO MYSALARY VALUES(2,8000)
INSERT INTO MYSALARY VALUES(3,5000)

CREATE TABLE MYPHONE (EMPLOYEEID INT, PHONENUMBER INT)
INSERT INTO MYPHONE VALUES(1,1234567680)
INSERT INTO MYPHONE VALUES(2,0987654321)

CREATE TABLE MYPARKING (EMPLOYEEID INT, PARKINGSPOT VARCHAR(20))
INSERT INTO MYPARKING VALUES(1,'a1')
INSERT INTO MYPARKING VALUES(2,'a2')

CREATE TABLE MYCSUTOMER (CUSTOMERID INT, CUSTOMERNAME VARCHAR(20))
INSERT INTO MYCSUTOMER VALUES(1,'BAD')
INSERT INTO MYCSUTOMER VALUES(3,'EVIL')

CREATE TABLE MYORDER (ORDERNUMBER INT, ORDERNAME VARCHAR(20),CUSTOMERID INT)
INSERT INTO MYORDER VALUES(1,'SOMEORDER1', 1)
INSERT INTO MYORDER VALUES(2,'SOMEORDER1', 2)
INSERT INTO MYORDER VALUES(3,'SOMEORDER3', 7)
INSERT INTO MYORDER VALUES(4,'SOMEORDER4', 8)

ALTER TABLE MYORDER
ADD ORDERDATE DATE

UPDATE MYORDER SET ORDERDATE=GETDATE()
WHERE ORDERNUMBER>2

UPDATE MYORDER SET ORDERDATE=GETDATE()-9
WHERE ORDERNUMBER<3

--SHOW ALL TABLES--
SELECT * FROM MYEMLOYEE
SELECT * FROM MYSALARY
SELECT * FROM MYPHONE
SELECT * FROM MYPARKING
SELECT * FROM MYCSUTOMER
SELECT * FROM MYORDER

--DELETE ALL ROWS --
TRUNCATE TABLE MYCSUTOMER

--DELETE PARTICULAR ROW --
DELETE FROM MYORDER WHERE ORDERDATE LIKE '2020-06-19'


--INNER JOIN--
SELECT A.FIRSTNAME, A.LASTNAME, B.SALARY 
FROM MYEMLOYEE A INNER JOIN MYSALARY B 
ON A.EMPLOYEID = B.EMPLOYEEID

--LEFT JOIN--
SELECT A.FIRSTNAME, A.LASTNAME, B.PHONENUMBER 
FROM MYEMLOYEE A LEFT JOIN MYPHONE B 
ON A.EMPLOYEID = B.EMPLOYEEID

--RIGHT JOIN--
SELECT A.PARKINGSPOT, B.FIRSTNAME, B.LASTNAME 
FROM MYPARKING A RIGHT JOIN MYEMLOYEE B 
ON A.EMPLOYEEID = B.EMPLOYEID

--FULL OUTER JOIN--
SELECT A.CUSTOMERID, A.CUSTOMERNAME,B.ORDERNUMBER, B.ORDERNAME 
FROM MYCSUTOMER A FULL OUTER JOIN MYORDER B
ON A.CUSTOMERID = B.CUSTOMERID

--CROSS JOIN--
SELECT * FROM MYCSUTOMER CROSS JOIN MYSALARY
SELECT * FROM MYCSUTOMER,MYSALARY

SELECT GETDATE()