--FUNCTIONS--

--AGGREGATE FUNCTIONS--
SELECT * FROM MYSALARY

SELECT AVG(SALARY) FROM MYSALARY

SELECT COUNT(SALARY) FROM MYSALARY

SELECT SUM(SALARY) FROM MYSALARY

SELECT MIN(SALARY) FROM MYSALARY

SELECT MAX(SALARY) FROM MYSALARY


SELECT * FROM MYORDER

--CONCAT--
PRINT CONCAT('String1','String2')

SELECT ORDERNUMBER, ORDERNAME, CONCAT(ORDERNAME, ' ', RAND()) AS CONCATENATEDTEXT FROM MYORDER


--LEFT--
SELECT ORDERNUMBER, ORDERNAME, LEFT(ORDERNAME, 5) FROM MYORDER

--RIGHT--
SELECT ORDERNUMBER, ORDERNAME, RIGHT(ORDERNAME, 5) FROM MYORDER

--SUBSTRING--
SELECT ORDERNUMBER, ORDERNAME, SUBSTRING(ORDERNAME, 3, 5) FROM MYORDER

--LOWERCASE--
SELECT ORDERNUMBER, ORDERNAME, LOWER(ORDERNAME) FROM MYORDER

--UPPERCASE--
SELECT ORDERNUMBER, ORDERNAME, UPPER(ORDERNAME) FROM MYORDER

--LENGTH--
SELECT ORDERNUMBER, ORDERNAME, LEN(ORDERNAME) FROM MYORDER

--CAMELCASE--
SELECT ORDERNUMBER, ORDERNAME, CONCAT(UPPER(LEFT(ORDERNAME,1)),LOWER(SUBSTRING(ORDERNAME,2,LEN(ORDERNAME)))) FROM MYORDER


--LEFT TRIM--
SELECT LTRIM('   text   '   )
--RIGHT TRIM 
SELECT RTRIM('   text   '   )
--trim on both sides--
SELECT LTRIM(RTRIM('   text book  '))
