--DATE--

SELECT GETDATE()
SELECT GETDATE()-2


--DATEPART--
SELECT DATEPART(yyyy, GETDATE()) AS YEARNUMBER
SELECT DATEPART(mm, GETDATE()) AS MONTHNUMBER
SELECT DATEPART(dd, GETDATE()) AS DATENUMER

--DATEADD--
SELECT DATEADD(day, 4, '7/4/2015')
SELECT DATEADD(day, 4, GETDATE())
SELECT DATEADD(year, 4, GETDATE())
SELECT DATEADD(month, 4, GETDATE())

--
SELECT TOP 3 * FROM [dbo].[MYORDER]

SELECT ORDERNUMBER, ORDERNAME, CUSTOMERID, ORDERDATE, DATEDIFF(day,ORDERDATE,GETDATE()) AS DAYS
FROM [dbo].[MYORDER]

SELECT DATEADD(dd, -(DATEPART(day, GETDATE())-1), GETDATE())